# version: '3.7'

# services:

#   sample:
#     container_name: sample
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#     ports:
#       - 1337:80
#     # environment:
#     #   - CHOKIDAR_USEPOLLING=true