// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	database "movie/repository/mongodb/database"

	mock "github.com/stretchr/testify/mock"
)

// ClientHelper is an autogenerated mock type for the ClientHelper type
type ClientHelper struct {
	mock.Mock
}

// Connect provides a mock function with given fields:
func (_m *ClientHelper) Connect() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database provides a mock function with given fields: _a0
func (_m *ClientHelper) Database(_a0 string) database.DatabaseHelper {
	ret := _m.Called(_a0)

	var r0 database.DatabaseHelper
	if rf, ok := ret.Get(0).(func(string) database.DatabaseHelper); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.DatabaseHelper)
		}
	}

	return r0
}
