// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	database "movie/repository/mongodb/database"

	mock "github.com/stretchr/testify/mock"
)

// DatabaseHelper is an autogenerated mock type for the DatabaseHelper type
type DatabaseHelper struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *DatabaseHelper) Client() database.ClientHelper {
	ret := _m.Called()

	var r0 database.ClientHelper
	if rf, ok := ret.Get(0).(func() database.ClientHelper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.ClientHelper)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: name
func (_m *DatabaseHelper) Collection(name string) database.CollectionHelper {
	ret := _m.Called(name)

	var r0 database.CollectionHelper
	if rf, ok := ret.Get(0).(func(string) database.CollectionHelper); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.CollectionHelper)
		}
	}

	return r0
}
