version: '3.8'

services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   container_name: mongo

  user: 
    build: 
      context: ./user
      dockerfile: Dockerfile
    image: asia.gcr.io/movie-app-339412/movie-user:dev
  
  cinema: 
    build: 
      context: ./cinema
      dockerfile: Dockerfile
    image: asia.gcr.io/movie-app-339412/movie-cinema:dev
  
  movie: 
    build: 
      context: ./movie/
      dockerfile: Dockerfile
    image: asia.gcr.io/movie-app-339412/movie-movie:dev
  
  reservation: 
    build: 
      context: ./reservation/
      dockerfile: Dockerfile
    image: asia.gcr.io/movie-app-339412/movie-reservation:dev
  
  showtime: 
    build:
      context: ./showtime/
      dockerfile: Dockerfile
    image: asia.gcr.io/movie-app-339412/movie-showtime:dev
  

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args: 
        REACT_APP_BASE_USER_URL: http://movie.api.whoisusefor.tk/users/users
        REACT_APP_BASE_MOVIE_URL: http://movie.api.whoisusefor.tk/movies/movies
        REACT_APP_BASE_SHOWTIME_URL: http://movie.api.whoisusefor.tk/showtimes/showtimes
        REACT_APP_BASE_RESERVATION_URL: http://movie.api.whoisusefor.tk/reservations/reservations
        REACT_APP_BASE_CINEMA_URL: http://movie.api.whoisusefor.tk/cinemas/cinemas
    image: asia.gcr.io/movie-app-339412/movie-booking:dev
    ports:
      - 8080:80
