version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo

  user: 
    build: 
      context: ./user
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      APP_PORT: :8080
      MONGODB_ENDPOINT: mongodb://mongo:27017
      MONGODB_NAME: movie-dev
      MONGODB_COLLECTION: users
      JWT_SECRET: 'ffsdlfk#sd/'
      GRPC_HOST: :5000
      PHOTO_URL: http://media:8080/media/upload
    depends_on:
      - mongo
  
  cinema: 
    build: 
      context: ./cinema
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      APP_PORT: :8080
      MONGODB_ENDPOINT: mongodb://mongo:27017
      MONGODB_NAME: movie-dev
      MONGODB_COLLECTION: cinemas
      GRPC_HOST: :5001
      GRPC_AUTH_HOST: user:5000
      PHOTO_URL: http://media:8080/media/upload
    depends_on:
      - mongo
      - user
  
  movie: 
    build: 
      context: ./movie/
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      APP_PORT: :8080
      MONGODB_ENDPOINT: mongodb://mongo:27017
      MONGODB_NAME: movie-dev
      MONGODB_COLLECTION: movies
      GRPC_AUTH_HOST: user:5000
      PHOTO_URL: http://media:8080/media/upload
    depends_on:
      - mongo
      - user
  
  reservation: 
    build: 
      context: ./reservation/
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    environment:
      APP_PORT: :8080
      APP_URL: :8004/checkin
      MONGODB_ENDPOINT: mongodb://mongo:27017
      MONGODB_NAME: movie-dev
      MONGODB_COLLECTION: reservations
      GRPC_HOST: :5002
      GRPC_AUTH_HOST: user:5000
      GRPC_CINEMA_HOST: cinema:5001
    depends_on:
      - mongo
      - user
      - cinema
  
  showtime: 
    build:
      context: ./showtime/
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    environment:
      APP_PORT: :8080
      MONGODB_ENDPOINT: mongodb://mongo:27017
      MONGODB_NAME: movie-dev
      MONGODB_COLLECTION: showtimes
      GRPC_AUTH_HOST: user:5000
    depends_on:
      - mongo
      - user
  
  media:
    build: 
      context: ./media
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args: 
        REACT_APP_BASE_USER_URL: http://localhost:8081/users
        REACT_APP_BASE_CINEMA_URL:  http://localhost:8082/cinemas
        REACT_APP_BASE_MOVIE_URL:  http://localhost:8083/movies
        REACT_APP_BASE_RESERVATION_URL:  http://localhost:8084/reservations
        REACT_APP_BASE_SHOWTIME_URL:  http://localhost:8085/showtimes
    ports:
      - 80:80