// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	input "reservation/service/invitation/input"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Invitation provides a mock function with given fields: _a0, _a1
func (_m *Service) Invitation(_a0 context.Context, _a1 []*input.InvitationInput) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*input.InvitationInput) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
