// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JWTService is an autogenerated mock type for the JWTService type
type JWTService struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: id
func (_m *JWTService) GenerateToken(id string) (*string, error) {
	ret := _m.Called(id)

	var r0 *string
	if rf, ok := ret.Get(0).(func(string) *string); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: encodedToken
func (_m *JWTService) ValidateToken(encodedToken string) (string, error) {
	ret := _m.Called(encodedToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(encodedToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encodedToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
