// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Upload provides a mock function with given fields: ctx, filename, file
func (_m *Storage) Upload(ctx context.Context, filename string, file multipart.File) (string, error) {
	ret := _m.Called(ctx, filename, file)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File) string); ok {
		r0 = rf(ctx, filename, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, multipart.File) error); ok {
		r1 = rf(ctx, filename, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
