// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: cinema/cinema.proto

package cinema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CinemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaIds []string `protobuf:"bytes,1,rep,name=cinemaIds,proto3" json:"cinemaIds,omitempty"`
}

func (x *CinemaRequest) Reset() {
	*x = CinemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_cinema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CinemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CinemaRequest) ProtoMessage() {}

func (x *CinemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_cinema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CinemaRequest.ProtoReflect.Descriptor instead.
func (*CinemaRequest) Descriptor() ([]byte, []int) {
	return file_cinema_cinema_proto_rawDescGZIP(), []int{0}
}

func (x *CinemaRequest) GetCinemaIds() []string {
	if x != nil {
		return x.CinemaIds
	}
	return nil
}

type CinemaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cinema []*Cinema `protobuf:"bytes,1,rep,name=cinema,proto3" json:"cinema,omitempty"`
}

func (x *CinemaReply) Reset() {
	*x = CinemaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_cinema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CinemaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CinemaReply) ProtoMessage() {}

func (x *CinemaReply) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_cinema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CinemaReply.ProtoReflect.Descriptor instead.
func (*CinemaReply) Descriptor() ([]byte, []int) {
	return file_cinema_cinema_proto_rawDescGZIP(), []int{1}
}

func (x *CinemaReply) GetCinema() []*Cinema {
	if x != nil {
		return x.Cinema
	}
	return nil
}

type Cinema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaId       string  `protobuf:"bytes,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TicketPrice    int32   `protobuf:"varint,3,opt,name=ticketPrice,proto3" json:"ticketPrice,omitempty"`
	City           string  `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	SeatsAvailable int32   `protobuf:"varint,5,opt,name=seatsAvailable,proto3" json:"seatsAvailable,omitempty"`
	Image          string  `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Seats          []*Seat `protobuf:"bytes,7,rep,name=seats,proto3" json:"seats,omitempty"`
}

func (x *Cinema) Reset() {
	*x = Cinema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_cinema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cinema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cinema) ProtoMessage() {}

func (x *Cinema) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_cinema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cinema.ProtoReflect.Descriptor instead.
func (*Cinema) Descriptor() ([]byte, []int) {
	return file_cinema_cinema_proto_rawDescGZIP(), []int{2}
}

func (x *Cinema) GetCinemaId() string {
	if x != nil {
		return x.CinemaId
	}
	return ""
}

func (x *Cinema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cinema) GetTicketPrice() int32 {
	if x != nil {
		return x.TicketPrice
	}
	return 0
}

func (x *Cinema) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Cinema) GetSeatsAvailable() int32 {
	if x != nil {
		return x.SeatsAvailable
	}
	return 0
}

func (x *Cinema) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Cinema) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat []int32 `protobuf:"varint,1,rep,packed,name=seat,proto3" json:"seat,omitempty"`
}

func (x *Seat) Reset() {
	*x = Seat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_cinema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_cinema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_cinema_cinema_proto_rawDescGZIP(), []int{3}
}

func (x *Seat) GetSeat() []int32 {
	if x != nil {
		return x.Seat
	}
	return nil
}

var File_cinema_cinema_proto protoreflect.FileDescriptor

var file_cinema_cinema_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x2f, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x22, 0x2d, 0x0a,
	0x0d, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x0b,
	0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x06, 0x63,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x63, 0x69, 0x6e,
	0x65, 0x6d, 0x61, 0x22, 0xd0, 0x01, 0x0a, 0x06, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x61, 0x74, 0x73, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x65,
	0x61, 0x74, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x65, 0x61, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x52,
	0x05, 0x73, 0x65, 0x61, 0x74, 0x73, 0x22, 0x1a, 0x0a, 0x04, 0x53, 0x65, 0x61, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65,
	0x61, 0x74, 0x32, 0x49, 0x0a, 0x0d, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x73, 0x12, 0x15, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x09, 0x5a,
	0x07, 0x2f, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cinema_cinema_proto_rawDescOnce sync.Once
	file_cinema_cinema_proto_rawDescData = file_cinema_cinema_proto_rawDesc
)

func file_cinema_cinema_proto_rawDescGZIP() []byte {
	file_cinema_cinema_proto_rawDescOnce.Do(func() {
		file_cinema_cinema_proto_rawDescData = protoimpl.X.CompressGZIP(file_cinema_cinema_proto_rawDescData)
	})
	return file_cinema_cinema_proto_rawDescData
}

var file_cinema_cinema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cinema_cinema_proto_goTypes = []interface{}{
	(*CinemaRequest)(nil), // 0: cinema.CinemaRequest
	(*CinemaReply)(nil),   // 1: cinema.CinemaReply
	(*Cinema)(nil),        // 2: cinema.Cinema
	(*Seat)(nil),          // 3: cinema.Seat
}
var file_cinema_cinema_proto_depIdxs = []int32{
	2, // 0: cinema.CinemaReply.cinema:type_name -> cinema.Cinema
	3, // 1: cinema.Cinema.seats:type_name -> cinema.Seat
	0, // 2: cinema.CinemaService.GetCinemas:input_type -> cinema.CinemaRequest
	1, // 3: cinema.CinemaService.GetCinemas:output_type -> cinema.CinemaReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cinema_cinema_proto_init() }
func file_cinema_cinema_proto_init() {
	if File_cinema_cinema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cinema_cinema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CinemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_cinema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CinemaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_cinema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cinema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_cinema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cinema_cinema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cinema_cinema_proto_goTypes,
		DependencyIndexes: file_cinema_cinema_proto_depIdxs,
		MessageInfos:      file_cinema_cinema_proto_msgTypes,
	}.Build()
	File_cinema_cinema_proto = out.File
	file_cinema_cinema_proto_rawDesc = nil
	file_cinema_cinema_proto_goTypes = nil
	file_cinema_cinema_proto_depIdxs = nil
}
