// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "movie/entities"

	input "movie/service/movie/input"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	output "movie/service/movie/output"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in
func (_m *Service) Create(ctx context.Context, in *input.MovieInput) (*output.Movie, error) {
	ret := _m.Called(ctx, in)

	var r0 *output.Movie
	if rf, ok := ret.Get(0).(func(context.Context, *input.MovieInput) *output.Movie); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *input.MovieInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in
func (_m *Service) Delete(ctx context.Context, in *input.MovieInput) error {
	ret := _m.Called(ctx, in)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *input.MovieInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, opt
func (_m *Service) List(ctx context.Context, opt *entities.PageOption) ([]*output.Movie, error) {
	ret := _m.Called(ctx, opt)

	var r0 []*output.Movie
	if rf, ok := ret.Get(0).(func(context.Context, *entities.PageOption) []*output.Movie); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*output.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.PageOption) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: ctx, in
func (_m *Service) Read(ctx context.Context, in *input.MovieInput) (*output.Movie, error) {
	ret := _m.Called(ctx, in)

	var r0 *output.Movie
	if rf, ok := ret.Get(0).(func(context.Context, *input.MovieInput) *output.Movie); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *input.MovieInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, in
func (_m *Service) Update(ctx context.Context, in *input.MovieInput) (*output.Movie, error) {
	ret := _m.Called(ctx, in)

	var r0 *output.Movie
	if rf, ok := ret.Get(0).(func(context.Context, *input.MovieInput) *output.Movie); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *input.MovieInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: ctx, in, filename, file
func (_m *Service) Upload(ctx context.Context, in *input.MovieInput, filename string, file multipart.File) (*output.Movie, error) {
	ret := _m.Called(ctx, in, filename, file)

	var r0 *output.Movie
	if rf, ok := ret.Get(0).(func(context.Context, *input.MovieInput, string, multipart.File) *output.Movie); ok {
		r0 = rf(ctx, in, filename, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *input.MovieInput, string, multipart.File) error); ok {
		r1 = rf(ctx, in, filename, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
